### ISSUE TITLE
Issue with security breach in Google Chrome - Password exposed.

### ISSUE THREAD

**Issue by HeitorMatt** [datasci4health/harena-space#192]
Request header is sending the password plainly, without any encryption or something of the sort.

**Comment by faguim** [comment]
I think there is no problem on sending password in plain text format, once we use https for encriptying the comunnication channel (I am not sure of this as I am not an expert on security).

Maybe we can encript, but it wouldn't improve security: [https://stackoverflow.com/questions/606179/what-encryption-algorithm-is-best-for-encrypting-cookies](https://stackoverflow.com/questions/606179/what-encryption-algorithm-is-best-for-encrypting-cookies)

**Comment by marcosfmmota** [comment]
Since we changed for session the Chrome warning disappeared, thus I'm going to close the issue.
