### ISSUE TITLE
[bugfix #32] Small problem with the signin modal

### ISSUE THREAD

**Issue by matheusmota** [datasci4health/harena-space#32]
I'm getting this (probably) small problem on the signin page.
Env: Firefox. Resolution: 1920x1080

![Screenshot from 2019-06-09 21-42-49](https://user-images.githubusercontent.com/5621338/59166440-1b8d0b80-8b00-11e9-9970-441fa7cec806.png)

**Comment by HeitorMatt** [comment]
@faguim I'm closing this issue.
